const specializations = [
  { arabic: "الطب العام", english: "GENERAL_MEDICINE" },
  { arabic: "طب الأطفال", english: "PEDIATRICS" },
  { arabic: "القلبية", english: "CARDIOLOGY" },
  { arabic: "طب الجلدية", english: "DERMATOLOGY" },
  { arabic: "العظام", english: "ORTHOPEDICS" },
  { arabic: "الأعصاب", english: "NEUROLOGY" },
  { arabic: "الجهاز الهضمي", english: "GASTROENTEROLOGY" },
  { arabic: "الغدد الصماء", english: "ENDOCRINOLOGY" },
  { arabic: "الكلى", english: "NEPHROLOGY" },
  { arabic: "أمراض الجهاز التنفسي", english: "PULMONOLOGY" },
  { arabic: "العيون", english: "OPHTHALMOLOGY" },
  { arabic: "أنف وأذن وحنجرة", english: "ENT" },
  { arabic: "الجهاز البولي", english: "UROLOGY" },
  { arabic: "نساء وتوليد", english: "OBSTETRICS_AND_GYNECOLOGY" },
  { arabic: "أمراض الأورام", english: "ONCOLOGY" },
  { arabic: "الأشعة", english: "RADIOLOGY" },
  { arabic: "الطب النفسي", english: "PSYCHIATRY" },
  { arabic: "التخدير", english: "ANESTHESIOLOGY" },
  { arabic: "الروماتولوجيا", english: "RHEUMATOLOGY" },
  { arabic: "أمراض الدم", english: "HEMATOLOGY" },
  { arabic: "الأمراض المعدية", english: "INFECTIOUS_DISEASES" },
  { arabic: "الحساسية والمناعة", english: "ALLERGY_AND_IMMUNOLOGY" },
  {
    arabic: "الطب الطبيعي وإعادة التأهيل",
    english: "PHYSICAL_MEDICINE_AND_REHABILITATION",
  },
  { arabic: "الطوارئ", english: "EMERGENCY_MEDICINE" },
  { arabic: "طب العائلة", english: "FAMILY_MEDICINE" },
  { arabic: "الطب للكبار", english: "GERIATRICS" },
  { arabic: "الطب النووي", english: "NUCLEAR_MEDICINE" },
  { arabic: "علم الأمراض", english: "PATHOLOGY" },
  { arabic: "جراحة التجميل", english: "PLASTIC_SURGERY" },
  { arabic: "جراحة القلب والصدر", english: "CARDIOTHORACIC_SURGERY" },
  { arabic: "جراحة القولون والمستقيم", english: "COLORECTAL_SURGERY" },
  { arabic: "جراحة اليد", english: "HAND_SURGERY" },
  { arabic: "جراحة الأطفال", english: "PEDIATRIC_SURGERY" },
  { arabic: "جراحة زرع الأعضاء", english: "TRANSPLANT_SURGERY" },
  { arabic: "جراحة الأوعية الدموية", english: "VASCULAR_SURGERY" },
  { arabic: "طب الأطفال المبتسرين", english: "NEONATOLOGY" },
  { arabic: "طب الألم", english: "PAIN_MEDICINE" },
  { arabic: "طب النوم", english: "SLEEP_MEDICINE" },
  { arabic: "الطب الرياضي", english: "SPORTS_MEDICINE" },
  { arabic: "طب الرعاية الحرجة", english: "CRITICAL_CARE_MEDICINE" },
  {
    arabic: "طب تناسلي",
    english: "REPRODUCTIVE_ENDOCRINOLOGY_AND_INFERTILITY",
  },
  { arabic: "الوراثة الطبية", english: "MEDICAL_GENETICS" },
  { arabic: "الطب التخدير للطيران", english: "AEROSPACE_MEDICINE" },
];
